@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Oct 27 20:48:00 -0500 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 067c4f26ae09474288c435369cd994ba --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_programMem_behav xil_defaultlib.tb_programMem -log elaborate.log"
call xelab  -wto 067c4f26ae09474288c435369cd994ba --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_programMem_behav xil_defaultlib.tb_programMem -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
